apiVersion: v1
kind: Service
metadata:
  namespace: daedalus-project-docs-staging
  name: daedalus-project-docs-staging
  labels:
    app: nginx
    role: project-docs-staging
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
    role: project-docs-staging
