apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: daedalus-project-docs-develop
  name: daedalus-project-docs-develop
  labels:
    app: daedalus-project-docs-develop
spec:
  selector:
    matchLabels:
      app: nginx
      role: project-docs-develop
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
        role: project-docs-develop
    spec:
      containers:
      - name: daedalus-project-docs-nginx
        image: daedalusproject/daedalus-project-docs-develop:__IMAGE_TAG__
        resources:
          limits:
            cpu: 20m
            memory: 20Mi
          requests:
            cpu: 20m
            memory: 20Mi
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 20
