apiVersion: v1
kind: Service
metadata:
  namespace: daedalus-project-docs-develop
  name: daedalus-project-docs-develop
  labels:
    app: nginx
    role: project-docs-develop
spec:
  ports:
  - port: 80
    targetPort: 8000
  selector:
    app: nginx
    role: project-docs-develop
