apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: daedalus-project-docs-develop
  name: daedalus-project-docs-develop-ingress
  annotations:
    nginx.ingress.kubernetes.io/http2-push-preload: "true"
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
 rules:
 - host: dev-docs.daedalus-project.io
   http:
     paths:
     - path: /
       backend:
         serviceName: daedalus-project-docs-develop
         servicePort: 8080
 tls:
 - hosts:
   - dev-docs.daedalus-project.io
   secretName: daedalus-project-docs-develop-cert
