---
apiVersion: v1
kind: Namespace
metadata:
  name: daedalus-project-docs
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: daedalus-project-docs
spec:
  hard:
    requests.cpu: "200m"
    requests.memory: 200Mi
    limits.cpu: "200m"
    limits.memory: 200Mi
    pods: "6"
---
apiVersion: v1
kind: Namespace
metadata:
  name: daedalus-project-docs-staging
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: daedalus-project-docs-staging
spec:
  hard:
    requests.cpu: "100m"
    requests.memory: 100Mi
    limits.cpu: "100m"
    limits.memory: 100Mi
    pods: "4"
---
apiVersion: v1
kind: Namespace
metadata:
  name: daedalus-project-docs-develop
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: daedalus-project-docs-develop
spec:
  hard:
    requests.cpu: "50m"
    requests.memory: 50Mi
    limits.cpu: "50m"
    limits.memory: 50Mi
    pods: "2"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-daedalus-project-deployer
  namespace: daedalus-project-docs
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-deployer
  namespace: daedalus-project-docs
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-deployer
  namespace: daedalus-project-docs
subjects:
- kind: ServiceAccount
  name: gitlab-daedalus-project-deployer
  namespace: daedalus-project-docs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-daedalus-project-deployer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-deployer
  namespace: daedalus-project-docs-develop
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-deployer
  namespace: daedalus-project-docs-develop
subjects:
- kind: ServiceAccount
  name: gitlab-daedalus-project-deployer
  namespace: daedalus-project-docs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-daedalus-project-deployer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-deployer
  namespace: daedalus-project-docs-staging
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-deployer
  namespace: daedalus-project-docs-staging
subjects:
- kind: ServiceAccount
  name: gitlab-daedalus-project-deployer
  namespace: daedalus-project-docs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-daedalus-project-deployer
