---
apiVersion: v1
kind: Namespace
metadata:
  name: daedalus-project-docs
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: daedalus-project-docs
spec:
  hard:
    requests.cpu: "400m"
    requests.memory: 400Mi
    limits.cpu: "600m"
    limits.memory: 600Mi
    pods: "8"
---
apiVersion: v1
kind: Namespace
metadata:
  name: daedalus-project-docs-staging
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: daedalus-project-docs-staging
spec:
  hard:
    requests.cpu: "360m"
    requests.memory: 360Mi
    limits.cpu: "460m"
    limits.memory: 460Mi
    pods: "4"
---
apiVersion: v1
kind: Namespace
metadata:
  name: daedalus-project-docs-develop
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mem-cpu-quota
  namespace: daedalus-project-docs-develop
spec:
  hard:
    requests.cpu: "360m"
    requests.memory: 360Mi
    limits.cpu: "460m"
    limits.memory: 460Mi
    pods: "4"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-daedalus-project-docs-deployer
  namespace: daedalus-project-docs
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-docs-deployer
  namespace: daedalus-project-docs
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-docs-deployer
  namespace: daedalus-project-docs
subjects:
- kind: ServiceAccount
  name: gitlab-daedalus-project-docs-deployer
  namespace: daedalus-project-docs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-daedalus-project-docs-deployer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-docs-deployer
  namespace: daedalus-project-docs-develop
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-docs-deployer
  namespace: daedalus-project-docs-develop
subjects:
- kind: ServiceAccount
  name: gitlab-daedalus-project-docs-deployer
  namespace: daedalus-project-docs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-daedalus-project-docs-deployer
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-docs-deployer
  namespace: daedalus-project-docs-staging
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["*"]
  verbs: ["*"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: gitlab-daedalus-project-docs-deployer
  namespace: daedalus-project-docs-staging
subjects:
- kind: ServiceAccount
  name: gitlab-daedalus-project-docs-deployer
  namespace: daedalus-project-docs
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gitlab-daedalus-project-docs-deployer
