apiVersion: v1
kind: Service
metadata:
  namespace: daedalus-project-docs
  name: daedalus-project-docs
  labels:
    app: nginx
    role: project-docs
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nginx
    role: project-docs
