FROM daedalusproject/base_td_agent_bit:201906171703
MAINTAINER Álvaro Castellano Vela <alvaro.castellano.vela@gmail.com>

COPY containers/td-agent-bit/conf/td-agent-bit.conf /etc/td-agent-bit/td-agent-bit.conf
